version: "3.9"

#NETWORD
networks: 
    reviews-network:
        name: reviews-network
        driver: bridge

services: 
    frontend-web:
        image: frontend-web-image
        networks: 
            - reviews-network
        volumes: 
            - ../frontend-web/:/usr/src/frontend-web
        ports: 
            - 3000:3000
        environment: 
            - PORT=3000
        depends_on: 
            - db
            
        