module.exports = {
    //Review
    CREATE_REVIEW: 'CREATE_REVIEW',
    UPDATE_REVIEW: 'UPDATE_REVIEW',
    HIDE_REVIEW: 'HIDE_REVIEW',
    BLOCK_REVIEW: 'BLOCK_REVIEW',
    CONFIRM_REVIEW: 'CONFIRM_REVIEW',
    DELETE_REVIEW: 'DELETE_REVIEW',
    
    //Category
    CREATE_CATEGORY: 'CREATE_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    BLOCK_CATEGORY: 'BLOCK_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',
    
    //Tag
    CREATE_TAG: 'CREATE_TAG',
    UPDATE_TAG: 'UPDATE_TAG',
    BLOCK_TAG: 'BLOCK_TAG',
    DELETE_TAG: 'DELETE_TAG',
    
    //user
    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    BLOCK_USER: 'BLOCK_USER',
    DELETE_USER: 'DELETE_USER',
    CHANGE_ROLE_USER: 'CHANGE_ROLE_USER',
}